Repository Outfit-of-the-Trip/OOTT-Android, pull requests merged in 2023-09, with the labels that each got.

#28 [Feat/#26] 친구 페이지 ui 수정 및 친구 추가,삭제 버튼 추가
  android/link-assets-manifest.json
  ios/OOTT.xcodeproj/project.pbxproj
  ios/OOTT/Info.plist
  ios/link-assets-manifest.json
  package-lock.json
  package.json
  react-native.config.js
  src/assets/images/DetailRecomendairplane.png
  src/assets/images/bottomlogo.png
  src/assets/images/friends.png
  src/assets/images/home.png
  src/assets/images/mypage.png
  src/assets/images/photozone.png
  src/assets/images/settings.png
  src/assets/images/ufriends.png
  src/assets/images/uhome.png
  src/assets/images/umypage.png
  src/assets/images/uphotozone.png
  src/components/CalendarModal.js
  src/components/DateChosse.js
  src/components/EmptyScreen.js
  src/components/Navigation/BottomTabNavigation.tsx
  src/components/Navigation/Navigation.js
  src/components/toggleisfriendmodal.js
  src/constants/Friendex.js
  src/constants/RecomendGarmet.js
  src/screens/HomeScreen/HomeScreen.js
  src/screens/MainScreen/DetailRecomend/DetailRecomend.js
  src/screens/MainScreen/DetailRecomend/RecomendBottom.js
  src/screens/MainScreen/DetailRecomend/RecomendOutter.js
  src/screens/MainScreen/DetailRecomend/RecomendShose.js
  src/screens/MainScreen/DetailRecomend/RecomendTop.js
  src/screens/MainScreen/FriendsLook/FriendsLook.js
  src/screens/MainScreen/MainScreen.js
  src/screens/MainScreen/Recomend/Recomend.js
  src/screens/MainScreen/ShoppingList/ShoppingList.js
  src/screens/PhotozoneScreen/PhotozoneScreen.js
Labels: feat, design

#41 Feat/#40
  android/app/src/main/AndroidManifest.xml
  package-lock.json
  package.json
  src/assets/images/adc.png
  src/assets/images/goodheart.png
  src/assets/images/goodheartfilled-240.png
  src/components/Navigation/Navigation.js
  src/screens/MypageScreen/AbataScreen.js
  src/screens/MypageScreen/ClosetScreen.js
  src/screens/MypageScreen/KeywordScreen.js
  src/screens/MypageScreen/MypageScreen.js
Labels: feat

#46 [Feat/#45] 마이페이지 수정
  src/assets/images/drawer.png
  src/components/Navigation/Navigation.js
  src/screens/MainScreen/MainScreen.js
  src/screens/MypageScreen/KeywordScreen.js
  src/screens/MypageScreen/MypageScreen.js
  src/screens/MypageScreen/SendInfoScreen.js
Labels: feat, refactor

#53 Feat/#49 KeywordScreen 기능 수정중
  src/screens/MypageScreen/KeywordScreen.js
Labels: feat

#55 [Refactor/#54] 친구 페이지 디자인 수정
  src/assets/images/camera.png
  src/screens/FriendScreen/FriendScreen.js
Labels: refactor

#56 Feat/#49 기능 구현중
  src/screens/MypageScreen/KeywordScreen.js
  src/states/atoms.js
Labels: feat

#60 [Refactor/#54]친구 페이지 수정
  src/screens/FriendScreen/FriendScreen.js
  src/screens/MypageScreen/ClosetScreen/Components/Closet.js
Labels: refactor

#62 feat: 이미지 업로드 기능
  android/app/src/main/AndroidManifest.xml
  src/components/Navigation/Navigation.js
  src/screens/MainScreen/MainScreen.js
  src/screens/MypageScreen/ClosetScreen/Components/Closet.js
  src/screens/MypageScreen/ClosetScreen/Components/Gallery.js
  src/screens/MypageScreen/MypageScreen.js
Labels: feat

#63 [Feat/#62] 잘못된 푸시 바로 잡음
  src/screens/FriendScreen/FriendScreen.js
Labels: refactor

#73 Feat/#68
  src/components/Navigation/Navigation.js
  src/components/ShowLog.js
  src/screens/IsFirstLoginScreen/IsFirstLoginScreen.js
  src/screens/MainScreen/MainScreen.js
  src/screens/MainScreen/Recomend/Recomend.js
Labels: feat, design
