Repository Outfit-of-the-Trip/OOTT-Android, pull requests merged in 2023-10, with the labels that each got.

#74 feat:초기세팅기능세팅중
  src/components/FirstLogin.js
  src/components/Navigation/Navigation.js
  src/components/ShowLog.js
  src/screens/FirstSetting/FirstSetting.js
  src/screens/IsFirstLoginScreen/IsFirstLoginScreen.js
  src/screens/MainScreen/MainScreen.js
  src/screens/MypageScreen/MypageScreen.js
Labels: feat, design

#75 feat:네비게이션오류해결&UI보완
  src/assets/images/avatarbtn.png
  src/assets/images/frinedbtn.png
  src/assets/images/moreb.png
  src/screens/FirstSetting/FirstSetting.js
  src/screens/MainScreen/MainScreen.js
  src/screens/MainScreen/Recomend/Recomend.js
Labels: feat, design

#76 feat:기능,UI수정
  src/screens/MainScreen/Recomend/Recomend.js
Labels: feat, design

#86 feat:patch요청수정중
  src/screens/MainScreen/MainScreen.js
  src/screens/MypageScreen/KeywordScreen.js
Labels: feat, design

#88 Feat/#87 UI 완성
  src/assets/images/adc.png
  src/assets/images/codybackground.png
  src/assets/images/friendbackground.png
  src/screens/MainScreen/FriendsLook/FriendsLook.js
  src/screens/MainScreen/MainScreen.js
  src/screens/MypageScreen/ClosetScreen/Components/Closet.js
  src/screens/MypageScreen/KeywordScreen.js
  src/screens/MypageScreen/MypageScreen.js
Labels: design

#89 [Feat/#84] 친구 요청 수락 페이지 추가
  src/components/Navigation/BottomTab.js
  src/components/Navigation/Navigation.js
  src/screens/FriendScreen/FriendRequestScreen.js
  src/screens/FriendScreen/FriendScreen.js
  src/screens/FriendScreen/FriendSelectScreen.js
Labels: feat

#98 [refactor/#80] 불필요한 구문들 정리
  package-lock.json
  package.json
  src/components/CalendarModal.js
  src/components/FirstLogin.js
  src/components/Navigation/Navigation.js
  src/screens/FirstSetting/FirstSetting.js
  src/screens/FriendScreen/FriendScreen.js
  src/screens/FriendScreen/FriendSelectScreen.js
  src/screens/MainScreen/FriendsLook/FriendsLook.js
  src/screens/MainScreen/MainScreen.js
  src/screens/MainScreen/ShoppingList/ShoppingList.js
  src/screens/MypageScreen/AbataScreen.js
  src/screens/MypageScreen/ClosetScreen/ClosetScreen.js
  src/screens/MypageScreen/ClosetScreen/Components/Bottom.js
  src/screens/MypageScreen/ClosetScreen/Components/Closet.js
  src/screens/MypageScreen/ClosetScreen/Components/Outer.js
  src/screens/MypageScreen/ClosetScreen/Components/Shoes.js
  src/screens/MypageScreen/ClosetScreen/Components/Top.js
  src/screens/MypageScreen/KeywordScreen.js
  src/screens/MypageScreen/MypageScreen.js
  src/screens/OOTTScreen/OOTTScreen.js
  src/screens/OOTTScreen/TravelCategory/TravelCategory.js
  src/screens/OOTTScreen/TravelPlace/TravelPlace.js
  src/screens/PhotozoneScreen/DetailModal.js
  src/screens/PhotozoneScreen/PhotozoneScreen.js
  src/screens/SettingScreen/SettingScreen.js
Labels: refactor

#100 [Rename/#99] 유니티 폴더 삭제
  src/screens/FriendScreen/FriendScreen.js
Labels: rename

#105 feat:로그인네비게이션수정
  src/components/Navigation/Navigation.js
  src/screens/MainScreen/MainScreen.js
Labels: feat

#107 feat:이미지데이터처리완료
  src/screens/MainScreen/MainScreen.js
Labels: feat

#109 feat:main오류해결
  src/screens/MainScreen/MainScreen.js
Labels: feat

#119 Feat/#119
  android/app/build.gradle
Labels: feat
